### ISSUE TITLE
API Doc - 404 Not Found repeatedly

### ISSUE THREAD

**Issue by cbzdok** [apigee/apigee-api-catalog-drupal#113]
Apigee API Catalog functionality appears inconsistent. Some API Docs i am able to pull up, others return with a 404 consistently and only half of the page renders. Is there some type of swagger size limit? I did verify that the swagger is valid. Here is the error I am seeing though when i uploaded the document no errors were returned. 

Request URL: https://116devclone-ally-developer-portal-2.pantheonsite.io/sites/default/files/apidoc_specs/ccn_6.yml
Request Method: GET
Status Code: 404 Not Found
Remote Address: 10.47.196.154:9191
Referrer Policy: strict-origin-when-cross-origin

Additional info: Swagger yml file is only 73KB, 2100 lines. Screenshot of screen render below. The same .yml file appears to be working on the older version of the Apigee API Catalog.

![Screen Shot 2020-11-10 at 6 22 06 PM](https://user-images.githubusercontent.com/1984777/98745493-ad4a1980-2381-11eb-8a17-59483611d7c2.png)

**Comment by kscheirer** [comment]
Did you follow all of these steps? https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/391#issuecomment-696251750

I think you upgraded to API Catalog 2.x before this was fixed, and your portal looks a lot like what I had at that time as well. The main problems are your field names need to be updated, and the card links on the homepage changed.

**Comment by cbzdok** [comment]
Thanks @kscheirer  for your response! Honestly I'm afraid to do anything with this module in fear that chaos will ensue again but I'll review your link above. I am now on the current version of API Catalog and the functionality of the API Docs is intermittent but consistent, if that makes sense. Either the API Doc renders perfectly every time or it never renders with a 404, even though i can see the file on the server. I'll review your link and make sure everything is squared away there.

Thanks again!

**Comment by cbzdok** [comment]
I followed all of the steps above however I am still getting the same issue of the 404 File Not Found for some of the .yml files i upload even though the file does exist on the server.

**Comment by arlina-espinoza** [comment]
Hi @cbzdok, it looks like the file itself cannot be found (ie, 404 on the file path) so it's not something of a limit on the swagger file size. Could you try posting a screenshot of the field names in your API Doc content type? (/admin/structure/types/manage/apidoc/fields). Thanks!

**Comment by minnur** [comment]
Similar issue happened with another site, no apigee installation, but also hosted on Pantheon. @cbzdok were you able to replicate the issue on your local development ?

**Comment by cbzdok** [comment]
I don’t have a local development environment but can replicate it consistently on pantheon.   
  
  
  
    
  

  
  
>

**Comment by giteshk** [comment]
@cbzdok 

Are you sure your URL is correct? 
This URL doesn't work : https://116devclone-ally-developer-portal-2.pantheonsite.io/sites/default/files/apidoc_specs/ccn_6.yml
This Works : https://116devclone-ally-developer-portal-2.pantheonsite.io/sites/default/files/apidoc_specs/ccn_6.yaml

There is a difference in the extensions that were used in both these files.

**Comment by cbzdok** [comment]
Yes i'm positive. I've uploaded a number of yaml files trying every combination to see why it works sometimes and not others. Please refer to the screenshot. I will also open a ticket with Pantheon to see if this is a hosting issue.

<img width="967" alt="Screen Shot 2020-12-08 at 9 57 16 AM" src="https://user-images.githubusercontent.com/1984777/101499890-c96ab780-393b-11eb-93b0-51fd55bdc038.png">

**Comment by cbzdok** [comment]
Well... came to understand that rendering .yml file extensions is not supported by Drupal 8 installations and the file would not be accessible. I will close the issue since this is not related to this module however perhaps in the catalog tooltip "Allowed types: yml yaml json." the yml extension maybe should be considered to be removed
