### ISSUE TITLE
when we are cicking on api spec we are getting this error

### ISSUE THREAD

**Issue by samuprad** [apigee/apigee-api-catalog-drupal#261]
## Description
The website encountered an unexpected error. Please try again later.

Symfony\Component\Routing\Exception\RouteNotFoundException: Route "view.apigee_api_catalog.page_1" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 206 of core/lib/Drupal/Core/Routing/RouteProvider.php).
Drupal\Core\Routing\UrlGenerator->getRoute() (Line: 270)
Drupal\Core\Routing\UrlGenerator->generateFromRoute() (Line: 105)
Drupal\Core\Render\MetadataBubblingUrlGenerator->generateFromRoute() (Line: 765)
Drupal\Core\Url->toString() (Line: 1765)
template_preprocess_breadcrumb()
call_user_func_array() (Line: 287)
Drupal\Core\Theme\ThemeManager->render() (Line: 433)
Drupal\Core\Render\Renderer->doRender() (Line: 204)
Drupal\Core\Render\Renderer->render() (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter() (Line: 47)
__TwigTemplate_a5d422e3b6b570d7a242278921e07f84->doDisplay() (Line: 405)
Twig\Template->displayWithErrorHandling() (Line: 378)
Twig\Template->display() (Line: 390)
Twig\Template->render() (Line: 55)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 433)
Drupal\Core\Render\Renderer->doRender() (Line: 446)
Drupal\Core\Render\Renderer->doRender() (Line: 204)
Drupal\Core\Render\Renderer->render() (Line: 581)
Drupal\Core\Template\TwigExtension->renderVar() (Line: 73)
__TwigTemplate_1f877ad6c7b5eea5c1815706a55e7801->doDisplay() (Line: 405)
Twig\Template->displayWithErrorHandling() (Line: 378)
Twig\Template->display() (Line: 390)
Twig\Template->render() (Line: 55)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 433)
Drupal\Core\Render\Renderer->doRender() (Line: 204)
Drupal\Core\Render\Renderer->render() (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter() (Line: 86)
__TwigTemplate_14738ce99ef38796cc1a74a2832ad55e->doDisplay() (Line: 405)
Twig\Template->displayWithErrorHandling() (Line: 378)
Twig\Template->display() (Line: 390)
Twig\Template->render() (Line: 55)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 433)
Drupal\Core\Render\Renderer->doRender() (Line: 204)
Drupal\Core\Render\Renderer->render() (Line: 162)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 580)
Drupal\Core\Render\Renderer->executeInRenderContext() (Line: 163)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse() (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray()
call_user_func() (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() (Line: 174)
Symfony\Component\HttpKernel\HttpKernel->handleRaw() (Line: 81)
Symfony\Component\HttpKernel\HttpKernel->handle() (Line: 58)
Drupal\Core\StackMiddleware\Session->handle() (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle() (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass() (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle() (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() (Line: 23)
Stack\StackedHttpKernel->handle() (Line: 718)
Drupal\Core\DrupalKernel->handle() (Line: 19)

## Steps to Reproduce
![image](https://github.com/user-attachments/assets/fda914c4-49da-43db-b2ce-c38a8d436a1b)

## Actual Behavior
What happened after the steps to reproduce.

## Version Info
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.

**Comment by kedarkhaire** [comment]
Hi @samuprad 
Can you please share more details, the version of Drupal, PHP, modules you are using.
Also share output of composer show.
Please provide steps to reproduce, as in our current setup we are not able to reproduce the above behavior.

Thanks!

**Comment by kedarkhaire** [comment]
Hi @samuprad 
Also it seems you have deleted this view `admin/structure/views/view/apigee_api_catalog/edit/page_1`
Can you please visit this path  & check and if the view is present or not.
This issue usually occurs when the above mentioned view is missing/deleted.
Do update post your check
Thanks!

**Comment by samuprad** [comment]
We haven't deleted the view.

**Comment by samuprad** [comment]
When we haveuploaded almost 100 plus api specs, ot was all working. We started classifying them into cateories, thats when the issue started. this is addtional note.

**Comment by kedarkhaire** [comment]
Thanks for the detail @samuprad . I hope you are categorizing with `Api Category` vocabulary terms.

As you are saying that you haven't deleted the view, then please visit this view `admin/structure/views/view/apigee_api_catalog/edit/page_1` and check for the Categories exposed setting in Filters section.

If you are using more than other vocabulary for your Api content, then do configure that in the filter setting.

Do let us know, it works for you.

Thanks!

**Comment by samuprad** [comment]
no it doesnt show that view
![image](https://github.com/user-attachments/assets/06c6577f-4f3a-479f-a667-1e0490638af0)

**Comment by samuprad** [comment]
one more observation, user is able to see the api spec, only adminstratior is not able to see.

I tried to clear cache fro UI but it doesnt work.

When i am installing Drush in server Linux 8.10 

its missing php.gd, while its extension is enabled. 

[root@DC10APGDPTADL02 bin]# sudo setenforce 0
setenforce: SELinux is disabled
[root@DC10APGDPTADL02 bin]# php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'gd' (tried: /usr/lib64/php/modules/gd (/usr/lib64/php/modules/gd: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/gd.so (libvmaf.so.1: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'gd' (tried: /usr/lib64/php/modules/gd (/usr/lib64/php/modules/gd: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/gd.so (libvmaf.so.1: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.1.29 (cli) (built: Jun  5 2024 05:51:57) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.29, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.29, Copyright (c), by Zend Technologies
[root@DC10APGDPTADL02 bin]# drush --version
bash: drush: command not found

**Comment by samuprad** [comment]
looks like Cache needs to be cleared. Let us know the best way to get this api doc module is back.

**Comment by kedarkhaire** [comment]
Hi @samuprad 
As I previously said, that you have deleted this view API Catalog  `admin/structure/views/view/apigee_api_catalog/edit/page_1`
As per your views listing image you do not have that view. You are having APIDoc Catlog Admin. You must have this view - **API Catalog**

This issue usually occurs when the above mentioned view is missing/deleted.

You can import this view from this [config file](https://github.com/apigee/apigee-api-catalog-drupal/blob/3.x/config/optional/views.view.apigee_api_catalog.yml). 

Visit from Admin menus -> Configuration >> Development >> Configuration Synchronization >> Import >> Single Item (Switch to this tab) [or directly use this `/admin/config/development/configuration/single/import` to visit above location]

Select _Configuration Type_ as **View** & paste the copied file contents from [config file](https://github.com/apigee/apigee-api-catalog-drupal/blob/3.x/config/optional/views.view.apigee_api_catalog.yml) to this field _Paste your configuration here_.

Hit _Import_ CTA and do let us know, if it worked for you.

For your php-gd issue, try installing via `apt-get install php-gd`

Drush installation use `composer require drush/drush`. For more details [check](https://www.drush.org/13.x/install/)

Thanks!

**Comment by samuprad** [comment]
Thank you it worked. I appreciate your fast response and analysis.

**Comment by samuprad** [comment]
but i still have some issues as shown in this screenshot

**Comment by samuprad** [comment]
it was asking for entity id. i think it replaced it but the specs are not visible. how to find the old entity id. 
![image](https://github.com/user-attachments/assets/f4ea6f24-a978-4e09-b6ea-68519ce22999)

**Comment by kedarkhaire** [comment]
> but i still have some issues as shown in this screenshot !

Hi @samuprad 
I am removing the above screenshot shared as it contains credentials information. Also, as this is a public forum, next time please check the images and remove the personal details before sharing. 
Thanks!

**Comment by kedarkhaire** [comment]
Hi @samuprad 
Also related to above query asked, please elaborate more in the new issue. 
As the scope of the current issue is fixed, if you feel the same, please close this issue and open new issue elaborating all the steps used, versions used of Drupal, PHP & the module version.

Thanks!

**Comment by samuprad** [comment]
Hi ,

The issue is not fixed, it doesn't show the API spec. As in the screen shot.

It shows blank page only.

Thanks Pradeep.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kedarkhaire** [comment]
Hi Pradeep, 

Can you check it with the below yaml. Save the below with yaml extension and create a new Open API spec. Check the output and do let us know, if it works.

```
openapi: 3.0.3
info:
  version: 0.9.2
  title: httpbin.org
  description: A simple HTTP Request & Response Service.

servers:
  - url: http://httpbin.org
  - url: https://httpbin.org

paths:
  /get:
    get:
      tags:
        - HTTP Methods
      summary: The request's query parameters.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /post:
    post:
      tags:
        - HTTP Methods
      summary: The request's POST parameters.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /delete:
    delete:
      tags:
        - HTTP Methods
      summary: The request's DELETE parameters.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /put:
    put:
      tags:
        - HTTP Methods
      summary: The request's PUT parameters.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object

  /patch:
    patch:
      tags:
        - HTTP Methods
      summary: The request's PATCH parameters.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /ip:
    get:
      tags:
        - HTTP Methods
      summary: Returns the requester's IP Address.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /user-agent:
    get:
      tags:
        - HTTP Methods
      summary: Return the incoming requests's User-Agent header.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /uuid:
    get:
      tags:
        - UUID
      summary: Return a UUID4.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
```

Thanks!

**Comment by samuprad** [comment]
we are not able to upload the api doc 
![image](https://github.com/user-attachments/assets/bd7e16ac-7cb5-46fe-9ffe-2d5c0cbbf161)

**Comment by kedarkhaire** [comment]
Did you try to save the above set of code in a file with extension .yaml and then try to upload in a new Open API Doc ?

Please let us know, set of steps you performed to do so.

Thanks!

**Comment by samuprad** [comment]
i as not able to upload, as the page for upload is showing as above screenshot

**Comment by samuprad** [comment]
can we schedule a meeting to understand the issue. Thanks in advance.

**Comment by kedarkhaire** [comment]
Hi @samuprad 
Yes, we are open for a call, please schedule for Wednesday IST post 2pm.
Thanks!

**Comment by samuprad** [comment]
please join 9am IST  https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDgxOGFmNjMtZTYxZS00YjE5LWE2ZTQtODMzODA4NTc0MzU1%40thread.v2/0?context=%7b%22Tid%22%3a%225e625f8d-0b53-4f56-9e46-19fa14bb2e5c%22%2c%22Oid%22%3a%22c6b2618e-5759-47cc-bb1a-589ac7919099%22%7d

**Comment by samuprad** [comment]
Hello please let us know how we can proceed.

**Comment by kedarkhaire** [comment]
@samuprad Can you update here, if the issue still exists ?

As we said earlier, the issue is not related to the Devportal, it is due to some modifications on the server level permissions.
The missing view, which was earlier deleted by is now restored.

Can you please install a new devportal setup and check again.

Thanks!

**Comment by kedarkhaire** [comment]
Closing this issue as no response from long time.
